### ISSUE TITLE
pcjs.org isn't updated

### ISSUE THREAD

**Issue by mihailik** [jeffpar/pcjs.v1#22]
You've gone through a release increments and a blog post without updating the site. Your latest blog post on video quirks and integer overflow doesn't come up there.

I wonder if it's a bug in auto-deploy scripts somewhere?

**Comment by jeffpar** [comment]
True. When pcjs.org was hosted on Azure, automatic deployment was the default. Since I moved to AWS, it's not. I was OK with occasionally deploying manually, but I suppose I should look into auto deployment on AWS.

I'm just a little paranoid about overly frequent updates, because I can't re-test all the different machine configurations before every commit.  Most commits don't have much risk of breaking anything, but some do.

**Comment by jeffpar** [comment]
I'm going to leave things as-is for now, which means that the pcjs.org website will be updated only when it feels like there are enough changes (which have also been sufficiently tested) to merit deployment--or on days like today, when a showstopper needs to get fixed.

Plus, I don't like checking in recompiled JavaScript files after every change.  I usually hold off checking in recompiled JavaScript until I'm much closer to doing a release.

The rule of thumb is: whenever you see a new release posted here, on GitHub, then you should see the same release posted to pcjs.org, too.
