### ISSUE TITLE
Boot files for each DOS version you have images for?

### ISSUE THREAD

**Issue by andrewbird** [jeffpar/pcjs.v1#30]
Hi Jeff,
   I'm working on a little side project for [dosemu2](https://github.com/stsp/dosemu2) which adds some testing for basic boot success of Dosemu. Since DOS images are not generally available in one place on the web except your pcjs site, I've been (ab?)using the /api feature to convert your .json back to .img to seed my tests. I see your [blog post](http://www.pcjs.org/blog/2015/12/10/) about bandwidth problems and hope I've not caused you any problems. It seems that json->img interface is no longer available on pcjs.org, and to be honest it seemed a little unfair for me to grab them in this way. What I'm looking for is a way for a developer who wants to test Dosemu to get the three boot files (ibmbio.com, ibmsys.com, command.com etc) for each OS you have. Would it be possible for you to provide the images in binary format alongside the json ones in the repo?

Thanks, Andrew

**Comment by jeffpar** [comment]
I'm sure your use of the API was fine, no worries.  One solution would be to clone the project onto your own local machine, start the Node web server, and then use the API on your own machine.  Would that work for you?  I _could_ look into putting binary disk images on archive.pcjs.org, which is where I store large PDFs and other binary files, but that would take some time, and that seems like something a site like archive.org or winworldpc.com should do instead.  I'm not really interested in getting into the software archive business.

One feature I'm planning to add to PCjs, however, is the ability to browse mounted disk contents from the browser, so that any file _inside_ a machine can also be downloaded with a single click.  However, that's not happening in the near future -- hopefully early next year.

**Comment by andrewbird** [comment]
Hi Jeff,
   Thanks for your help. Since this test suite is hopefully going to be run by other developers, I can't really ask them to install PSjs, node etc, just to get the test images. I'm going to look at those two sites you mention and see if I can use them instead. I guess the most important thing is that they don't change location etc. I can't really ask you to host the images, as I'm not prepared to do it myself. I work with free software usually and it seems to be crossing a line for me to host even old stuff that really belongs to someone else.

Thanks again,

Andrew
