### ISSUE TITLE
Windows 3.1 (VGA) color palette is incorrect

### ISSUE THREAD

**Issue by jeffpar** [jeffpar/pcjs.v1#35]
The [Windows 3.1 demo machine](http://www.pcjs.org/disks/pc/windows/3.10/) illustrates the problem.

<img width="792" alt="screen shot 2016-04-03 at 6 04 29 pm" src="https://cloud.githubusercontent.com/assets/645749/14236210/8d41d658-f9c6-11e5-9176-d00b2f1ee422.png">

**Comment by gammaboost** [comment]
Windows 1.01-2.03 startup also not correct.

**Comment by gammaboost** [comment]
And windows 3.1 ega has white background instead of blue.
Windows 3.00 mouse on SETUP does not work.
Windows 3.1 ega mouse says mouse not installed. Mouse only works on setup.

![screenshot 2017-12-28 at 7 05 12 pm](https://user-images.githubusercontent.com/34908090/34404508-19bccf8c-ec02-11e7-9711-54f707bbc58c.png)

**Comment by jeffpar** [comment]
Thanks. Can you be more specific about what’s not correct about Windows 1.01-2.03?

**Comment by gammaboost** [comment]
On Windows 1.00 up to 2.03 (including the 386 versions), instead of having a blue startup background, there is a black startup background.

Windows 1.01 main demo on ega (startup):
![fae2cf31-87ae-46ce-bf7f-ce6fe4e25dab](https://user-images.githubusercontent.com/34908090/34457563-87bb537a-ee08-11e7-83fa-23289e1d2b3e.jpeg)

The picture above is supposed to have a blue startup, not black. This machine does support colour.

![37512495-06b2-4de9-89c1-2c43f0af9c1a](https://user-images.githubusercontent.com/34908090/34457572-c1f2152e-ee08-11e7-846b-82fb3633e20b.jpeg)

**Comment by jeffpar** [comment]
Colors on VGA video cards have been fixed.
