### ISSUE TITLE
Two BIOS beeps on 386 machine

### ISSUE THREAD

**Issue by yuhong** [jeffpar/pcjs.v1#40]
Go to http://www.pcjs.org/disks/pc/windows/win95/4.00.950/debugger/ . Click "Reset" then "Run". Two beeps occur.

**Comment by jeffpar** [comment]
I will investigate eventually--too many things to do. Here's one work-around: create a machine with the ChipSet 'sound' property set to false (it defaults to true if unspecified). ;-)

**Comment by yuhong** [comment]
Except that the machines hangs afterwards. This is a serious problem.

**Comment by jeffpar** [comment]
Ah, well, there was a recent regression that causes 80386-model machines to run at 4.77Mhz, which is too slow and might make the machine seem like it's hung.  That will be fixed when I roll out v1.22.1.

**Comment by yuhong** [comment]
Yes this is an important bug too.

**Comment by yuhong** [comment]
The speed bug is fixed now, and Win95 now boots after the beeps too.

**Comment by jeffpar** [comment]
The two beeps are by design (see excerpt from COMPAQ Technical Reference below).  If you were to run COMPAQ's MODE command to change the speed (eg, "MODE SPEED=COMMON") and reboot, you get only one beep.  So I don't think there's a real problem here.

<img width="758" alt="screen shot 2018-05-24 at 2 22 02 pm" src="https://user-images.githubusercontent.com/645749/40516598-29f81190-5f66-11e8-88e2-89e3ed97b9de.png">
