### ISSUE TITLE
On Website: Windows 95 Won't Detect Floppys

### ISSUE THREAD

**Issue by KittoDevv** [jeffpar/pcjs.v1#57]
So Yeah, Im Using A Chromebook, Trying some stuff on windows 95, Trying to use a floppy Then It Shows "Error Reading A:/; Device Not Ready" Could you fix it?

**Comment by jeffpar** [comment]
That used to be a problem, but I fixed it recently.  It's possible that the fix is unreliable, or dependent on the disk.  I tried a disk below, and it worked.

<img width="998" alt="screen shot 2018-03-15 at 12 04 08 pm" src="https://user-images.githubusercontent.com/645749/37485564-0e004f42-2849-11e8-8da7-e81dd13465a8.png">

**Comment by jeffpar** [comment]
In the absence of new information, I'm going to assume this is fixed.
