### ISSUE TITLE
Fullscreen has weird behavior on Chrome

### ISSUE THREAD

**Issue by Sgeo** [jeffpar/pcjs.v1#79]
On Chrome 75 on Windows, the fullscreen button seems to leave a lot of the virtual screen off of the visible screen. On Firefox, the fullscreen button seems fine, and there are black bars at the edges of the screen, which I assume is aspect ratio related?

**Comment by jeffpar** [comment]
Ah, the joy of keeping up with browser changes.  It looks like Chrome (and Edge) have altered their fullscreen support to behave more like Firefox.  Safari is still a holdout, so I still must have two different code paths for scaling the canvas in fullscreen mode.  Hopefully if/when Safari ever changes too, it will also define the standard *fullscreenEnabled* property, which will automatically trigger the new behavior.  And hopefully Edge will define that someday as well, so that I don't have to explicitly check the agent string for "Edge".  *sigh*

I've bumped the PCx86 version to 1.75.4, so make sure you're running the latest version, and let me know if your problem is resolved. It should be....

**Comment by Sgeo** [comment]
Tested on main pcjs.org website, works fine now, thank you :).
